# Features Configuration
# Defines feature engineering pipeline and parameters

features:
  # Global feature settings
  global:
    enabled: true
    cache_ttl: 3600  # Cache features for 1 hour
    max_history_days: 252  # 1 trading year
    min_required_data_points: 20
    
  # Feature calculation settings
  calculation:
    batch_size: 100
    parallel_workers: 4
    timeout_seconds: 300
    retry_attempts: 3
    
  # Feature categories
  categories:
    technical:
      enabled: true
      weight: 0.4
      
    fundamental:
      enabled: true
      weight: 0.3
      
    sentiment:
      enabled: true
      weight: 0.2
      
    macro:
      enabled: true
      weight: 0.1

# Technical Features
technical:
  moving_averages:
    enabled: true
    periods: [5, 10, 20, 50, 100, 200]
    types: ["sma", "ema", "wma"]
    
  momentum:
    enabled: true
    rsi:
      period: 14
      overbought: 70
      oversold: 30
    
    macd:
      fast_period: 12
      slow_period: 26
      signal_period: 9
    
    stochastic:
      k_period: 14
      d_period: 3
      overbought: 80
      oversold: 20
    
    williams_r:
      period: 14
      
    roc:
      periods: [5, 10, 20]
  
  volatility:
    enabled: true
    
    bollinger_bands:
      period: 20
      std_dev: 2.0
      
    atr:
      period: 14
      
    volatility_ratio:
      short_period: 10
      long_period: 30
      
    garch:
      enabled: false  # Computationally expensive
      
  volume:
    enabled: true
    
    volume_sma:
      periods: [10, 20, 50]
      
    volume_ratio:
      enabled: true
      
    obv:
      enabled: true
      
    vwap:
      enabled: true
      
    money_flow:
      enabled: true
      period: 14
      
  patterns:
    enabled: true
    
    candlestick:
      enabled: true
      patterns: ["doji", "hammer", "shooting_star", "engulfing"]
      
    chart_patterns:
      enabled: false  # Complex to implement
      
    support_resistance:
      enabled: true
      lookback_days: 30
      
  trend:
    enabled: true
    
    adx:
      period: 14
      
    aroon:
      period: 25
      
    parabolic_sar:
      acceleration: 0.02
      maximum: 0.2

# Fundamental Features
fundamental:
  financial_ratios:
    enabled: true
    
    profitability:
      - "gross_margin"
      - "operating_margin"
      - "net_margin"
      - "roe"
      - "roa"
      - "roic"
      
    liquidity:
      - "current_ratio"
      - "quick_ratio"
      - "cash_ratio"
      
    leverage:
      - "debt_to_equity"
      - "debt_to_assets"
      - "interest_coverage"
      
    efficiency:
      - "asset_turnover"
      - "inventory_turnover"
      - "receivables_turnover"
      
    valuation:
      - "pe_ratio"
      - "pb_ratio"
      - "ps_ratio"
      - "peg_ratio"
      - "ev_ebitda"
      
  growth_metrics:
    enabled: true
    periods: ["1q", "4q", "1y", "3y", "5y"]
    
    revenue_growth:
      enabled: true
      
    earnings_growth:
      enabled: true
      
    book_value_growth:
      enabled: true
      
    dividend_growth:
      enabled: true
      
  quality_metrics:
    enabled: true
    
    earnings_quality:
      enabled: true
      
    balance_sheet_quality:
      enabled: true
      
    cash_flow_quality:
      enabled: true
      
  estimates:
    enabled: true
    
    analyst_ratings:
      enabled: true
      
    earnings_estimates:
      enabled: true
      periods: ["1q", "2q", "fy1", "fy2"]
      
    revision_trends:
      enabled: true
      lookback_days: 30

# Sentiment Features
sentiment:
  news_sentiment:
    enabled: true
    
    sources:
      - "bloomberg"
      - "reuters"
      - "cnbc"
      - "yahoo"
      - "seeking_alpha"
      
    sentiment_model: "vader"  # vader, textblob, custom
    
    aggregation:
      periods: ["1d", "3d", "1w", "1m"]
      weights: [0.4, 0.3, 0.2, 0.1]
      
    keywords:
      positive: ["growth", "profit", "beat", "strong", "bullish"]
      negative: ["loss", "decline", "weak", "bearish", "concerns"]
      
  social_sentiment:
    enabled: true
    
    platforms:
      reddit:
        enabled: true
        subreddits: ["stocks", "investing", "wallstreetbets", "SecurityAnalysis"]
        
      twitter:
        enabled: false  # API costs
        
      stocktwits:
        enabled: true
        
    sentiment_aggregation:
      periods: ["1d", "3d", "1w"]
      min_mentions: 10
      
  analyst_sentiment:
    enabled: true
    
    rating_changes:
      enabled: true
      weight: 0.6
      
    price_target_changes:
      enabled: true
      weight: 0.4
      
    consensus_metrics:
      enabled: true

# Cross-Asset Features
cross_asset:
  enabled: true
  
  market_regime:
    enabled: true
    
    vix_levels:
      enabled: true
      
    yield_curve:
      enabled: true
      
    sector_rotation:
      enabled: true
      
  correlations:
    enabled: true
    
    spy_correlation:
      enabled: true
      period: 30
      
    sector_correlation:
      enabled: true
      period: 30
      
    peer_correlation:
      enabled: true
      period: 30
      
  relative_strength:
    enabled: true
    
    vs_market:
      enabled: true
      
    vs_sector:
      enabled: true
      
    vs_peers:
      enabled: true

# Feature Engineering Pipeline
pipeline:
  stages:
    - name: "data_validation"
      enabled: true
      
    - name: "technical_calculation"
      enabled: true
      depends_on: ["data_validation"]
      
    - name: "fundamental_calculation"
      enabled: true
      depends_on: ["data_validation"]
      
    - name: "sentiment_calculation"
      enabled: true
      depends_on: ["data_validation"]
      
    - name: "cross_asset_calculation"
      enabled: true
      depends_on: ["technical_calculation", "fundamental_calculation"]
      
    - name: "feature_selection"
      enabled: true
      depends_on: ["technical_calculation", "fundamental_calculation", "sentiment_calculation", "cross_asset_calculation"]
      
    - name: "feature_scaling"
      enabled: true
      depends_on: ["feature_selection"]
      
    - name: "feature_validation"
      enabled: true
      depends_on: ["feature_scaling"]

# Feature Selection
feature_selection:
  enabled: true
  
  methods:
    correlation_filter:
      enabled: true
      threshold: 0.95
      
    variance_filter:
      enabled: true
      threshold: 0.01
      
    mutual_information:
      enabled: true
      k_features: 100
      
    recursive_elimination:
      enabled: false  # Computationally expensive
      
  max_features: 200
  min_features: 50

# Feature Scaling
feature_scaling:
  method: "robust"  # standard, minmax, robust
  
  per_feature_scaling:
    enabled: true
    
  clip_outliers:
    enabled: true
    lower_quantile: 0.01
    upper_quantile: 0.99

# Feature Validation
validation:
  enabled: true
  
  checks:
    null_values:
      max_null_pct: 0.05
      
    infinite_values:
      allow_inf: false
      
    outlier_detection:
      method: "iqr"  # iqr, zscore, isolation_forest
      threshold: 3.0
      
    feature_drift:
      enabled: true
      threshold: 0.1
      
    correlation_stability:
      enabled: true
      threshold: 0.2

# Caching and Performance
caching:
  enabled: true
  backend: "redis"  # redis, memory, file
  
  cache_levels:
    raw_data: 3600      # 1 hour
    features: 1800      # 30 minutes
    aggregated: 300     # 5 minutes
    
  cache_keys:
    prefix: "features:"
    include_version: true
    include_timestamp: true

# Monitoring
monitoring:
  enabled: true
  
  metrics:
    calculation_time: true
    cache_hit_rate: true
    feature_quality: true
    data_freshness: true
    
  alerts:
    calculation_timeout: 300
    cache_miss_rate: 0.5
    feature_null_rate: 0.1
    
  dashboards:
    feature_health: true
    performance_metrics: true
    data_quality: true