# Network Configuration
# HTTP client and network settings for all external connections

network:
  # Global HTTP client settings
  http_client:
    timeout_seconds: 30
    connect_timeout: 10
    read_timeout: 20
    user_agent: 'AI-Trader/1.0'
    
    # Headers
    default_headers:
      Accept: 'application/json'
      Accept-Encoding: 'gzip, deflate'
    
    # SSL/TLS settings
    verify_ssl: true
    ssl_cert_path: null
    ssl_key_path: null
    
  # Connection pool configuration
  connection_pool:
    total_limit: 100
    per_host_limit: 10
    ttl_dns_cache: 300
    use_dns_cache: true
    enable_cleanup_closed: true
    
    # Keep-alive settings
    keepalive_timeout: 90
    keepalive_expiry: 600
    force_close_idle_after: 900
    
  # Session management
  session_management:
    warn_on_unclosed: true
    auto_cleanup: true
    max_sessions: 50
    session_timeout: 3600
    
  # Proxy configuration
  proxy:
    enabled: false
    http_proxy: ${HTTP_PROXY}
    https_proxy: ${HTTPS_PROXY}
    no_proxy: ${NO_PROXY}
    proxy_auth:
      username: ${PROXY_USERNAME}
      password: ${PROXY_PASSWORD}
      
  # WebSocket configuration
  websocket:
    ping_interval: 30
    pong_timeout: 10
    close_timeout: 10
    max_message_size: 10485760  # 10MB
    compression: 'deflate'
    
    # Reconnection settings
    auto_reconnect: true
    reconnect_interval: 5
    max_reconnect_attempts: 10
    backoff_multiplier: 1.5
    
  # Retry configuration (global defaults)
  retry:
    max_retries: 3
    retry_on_status: [429, 500, 502, 503, 504]
    retry_on_exception: ['ConnectionError', 'Timeout', 'ReadTimeout']
    backoff_factor: 0.5
    max_backoff: 120
    
  # Circuit breaker (global defaults)
  circuit_breaker:
    enabled: true
    failure_threshold: 5
    success_threshold: 2
    timeout: 60
    half_open_requests: 3
    
# Service-specific overrides
service_overrides:
  polygon:
    http_client:
      timeout_seconds: 60
      user_agent: 'AI-Trader/1.0 (Polygon)'
    connection_pool:
      per_host_limit: 15
    websocket:
      compression: null  # Polygon doesn't support compression
      
  alpaca:
    http_client:
      timeout_seconds: 45
    connection_pool:
      per_host_limit: 20
      
  yahoo:
    http_client:
      timeout_seconds: 90  # Yahoo can be slow
    connection_pool:
      per_host_limit: 5
    retry:
      max_retries: 5  # Yahoo is less reliable
      
  reddit:
    http_client:
      user_agent: 'AI-Trader/1.0 (by /u/aitrader)'  # Reddit requires specific UA
    connection_pool:
      per_host_limit: 2  # Reddit has strict limits
      
# Network monitoring
monitoring:
  # Track connection metrics
  metrics:
    enabled: true
    track_dns_time: true
    track_connect_time: true
    track_response_time: true
    track_total_time: true
    
  # Connection pool monitoring
  pool_monitoring:
    log_pool_stats: true
    log_interval_seconds: 300
    warn_on_exhaustion: true
    
  # Slow request logging
  slow_requests:
    enabled: true
    threshold_ms: 5000
    log_headers: false
    log_body: false