# Risk Management Configuration
# Defines risk limits, controls, and monitoring parameters

risk_management:
  # Global risk settings
  global:
    enabled: true
    max_portfolio_risk: 0.015     # 1.5% daily VaR
    max_drawdown: 0.12           # 12% maximum drawdown
    confidence_level: 0.95       # 95% confidence level for VaR

  # Portfolio level limits
  portfolio:
    max_gross_exposure: 1.00     # 100% gross exposure
    max_net_exposure: 0.95       # 95% net exposure
    max_leverage: 2.0            # 2x maximum leverage

    # Concentration limits
    max_single_position: 0.05    # 5% max single position
    max_sector_exposure: 0.30    # 30% max sector exposure
    max_country_exposure: 0.80   # 80% max country exposure

    # Correlation limits
    max_correlation_exposure: 0.40  # 40% max exposure to correlated assets
    correlation_threshold: 0.7      # Assets with >70% correlation

# Position Level Risk Controls
position_risk:
  # Position sizing
  position_sizing:
    method: "volatility_parity"  # fixed, volatility_parity, kelly, risk_parity

    volatility_parity:
      target_volatility: 0.12   # 12% target volatility
      lookback_period: 30       # 30 days for volatility calculation

    kelly:
      enabled: false            # Disabled - can be aggressive
      max_kelly_fraction: 0.25  # Maximum 25% of Kelly recommendation

    risk_parity:
      enabled: true
      risk_contribution_target: 0.05  # 5% equal risk contribution

  # Stop losses
  stop_losses:
    enabled: true

    # Fixed stop loss
    fixed_stop:
      enabled: true
      percentage: 0.08          # 8% stop loss

    # Volatility-based stop loss
    volatility_stop:
      enabled: true
      multiplier: 2.0           # 2x ATR stop loss
      period: 14                # 14-day ATR

    # Trailing stop loss
    trailing_stop:
      enabled: true
      percentage: 0.05          # 5% trailing stop
      activation_profit: 0.10   # Activate after 10% profit

    # Time-based stop
    time_stop:
      enabled: true
      max_hold_days: 30         # Close position after 30 days

  # Take profits
  take_profits:
    enabled: true

    # Fixed take profit
    fixed_profit:
      enabled: true
      percentage: 0.20          # 20% take profit

    # Volatility-based take profit
    volatility_profit:
      enabled: true
      multiplier: 3.0           # 3x ATR take profit
      period: 14

    # Partial profit taking
    partial_profits:
      enabled: true
      levels:
        - profit: 0.10
          percentage: 0.25      # Take 25% profit at 10% gain
        - profit: 0.15
          percentage: 0.50      # Take 50% profit at 15% gain

# Market Risk Controls
market_risk:
  # Market regime detection
  regime_detection:
    enabled: true

    indicators:
      vix_threshold: 25         # High volatility threshold
      yield_curve_inversion: true
      credit_spreads: true

    regime_actions:
      high_volatility:
        reduce_exposure: 0.20   # Reduce exposure by 20%
        increase_cash: 0.15     # Increase cash to 15%

      bear_market:
        max_exposure: 0.60      # Maximum 60% exposure
        hedge_ratio: 0.30       # 30% hedge ratio

  # Sector rotation monitoring
  sector_rotation:
    enabled: true

    momentum_threshold: 0.05    # 5% momentum threshold
    rebalance_frequency: "weekly"

    defensive_sectors:
      - "utilities"
      - "consumer_staples"
      - "healthcare"

  # Currency risk (for international assets)
  currency_risk:
    enabled: false              # Disabled for US-only strategy
    max_currency_exposure: 0.20
    hedge_ratio: 0.50

# Liquidity Risk Controls
liquidity_risk:
  # Minimum liquidity requirements
  minimum_liquidity:
    avg_daily_volume: 1000000   # $1M average daily volume
    bid_ask_spread: 0.02        # 2% maximum bid-ask spread
    market_cap: 1000000000      # $1B minimum market cap

  # Position size limits based on liquidity
  liquidity_scaling:
    enabled: true

    # Scale position size based on average daily volume
    volume_scaling:
      max_adv_percentage: 0.05  # Maximum 5% of average daily volume

    # Scale based on market cap
    market_cap_scaling:
      small_cap_limit: 0.02     # 2% for small cap (<$2B)
      mid_cap_limit: 0.03       # 3% for mid cap ($2B-$10B)
      large_cap_limit: 0.05     # 5% for large cap (>$10B)

  # Liquidity monitoring
  liquidity_monitoring:
    enabled: true

    alert_thresholds:
      volume_drop: 0.50         # Alert if volume drops 50%
      spread_widening: 2.0      # Alert if spread widens 2x

    emergency_actions:
      reduce_position: 0.50     # Reduce position by 50%
      increase_monitoring: true

# Operational Risk Controls
operational_risk:
  # Order management
  order_management:
    max_order_size: 0.05        # 5% max order size
    max_orders_per_minute: 10
    max_orders_per_day: 100

    # Order validation
    pre_trade_checks:
      enabled: true

      checks:
        - "position_limits"
        - "risk_limits"
        - "liquidity_checks"
        - "margin_requirements"

    # Order execution monitoring
    execution_monitoring:
      enabled: true

      slippage_alerts:
        warning_threshold: 0.01  # 1% slippage warning
        critical_threshold: 0.02 # 2% slippage critical

      fill_rate_monitoring:
        min_fill_rate: 0.90     # 90% minimum fill rate

  # System monitoring
  system_monitoring:
    enabled: true

    connectivity:
      max_downtime_minutes: 5
      backup_systems: true

    data_quality:
      max_stale_data_minutes: 10
      data_completeness: 0.95

    performance:
      max_latency_ms: 1000
      max_memory_usage: 0.80    # 80% max memory usage

# Stress Testing
stress_testing:
  enabled: true

  # Historical stress tests
  historical_scenarios:
    - name: "2008_financial_crisis"
      start_date: "2008-09-01"
      end_date: "2009-03-01"

    - name: "2020_covid_crash"
      start_date: "2020-02-01"
      end_date: "2020-04-01"

    - name: "2022_rate_hikes"
      start_date: "2022-01-01"
      end_date: "2022-12-31"

  # Hypothetical stress tests
  hypothetical_scenarios:
    - name: "market_crash"
      market_drop: 0.20         # 20% market drop
      volatility_spike: 2.0     # 2x volatility spike

    - name: "sector_rotation"
      sector_rotation_speed: 0.15  # 15% sector rotation

    - name: "liquidity_crisis"
      volume_drop: 0.50         # 50% volume drop
      spread_widening: 3.0      # 3x spread widening

  # Monte Carlo simulation
  monte_carlo:
    enabled: true
    num_simulations: 10000
    confidence_levels: [0.95, 0.99]

  # Frequency
  frequency: "weekly"

  # Actions based on stress test results
  stress_actions:
    var_breach_threshold: 0.02  # 2% VaR breach
    max_loss_threshold: 0.10    # 10% max loss

    actions:
      - "reduce_exposure"
      - "increase_hedging"
      - "notify_risk_manager"

# Real-time Risk Monitoring
real_time_monitoring:
  enabled: true

  # Monitoring frequency
  monitoring_frequency: 30     # 30 seconds

  # Real-time metrics
  metrics:
    - "portfolio_pnl"
    - "var_utilization"
    - "position_concentrations"
    - "sector_exposures"
    - "correlation_risk"

  # Alert thresholds
  alerts:
    # P&L alerts
    daily_loss_threshold: 0.02  # 2% daily loss
    intraday_loss_threshold: 0.015  # 1.5% intraday loss

    # Risk metric alerts
    var_utilization_threshold: 0.80  # 80% VaR utilization
    concentration_threshold: 0.08    # 8% concentration

    # Position alerts
    position_size_breach: 0.06      # 6% position size
    stop_loss_breach: true

  # Circuit breakers
  circuit_breakers:
    enabled: true

    triggers:
      daily_loss: 0.03          # 3% daily loss
      var_breach: 2.0           # 2x VaR breach
      system_error: true

    actions:
      - "stop_trading"
      - "flatten_positions"
      - "notify_risk_manager"
      - "emergency_hedging"

# Risk Reporting
reporting:
  enabled: true

  # Report frequency
  daily_report: true
  weekly_report: true
  monthly_report: true

  # Report content
  content:
    - "portfolio_summary"
    - "risk_metrics"
    - "position_analysis"
    - "performance_attribution"
    - "stress_test_results"
    - "limit_utilization"

  # Distribution
  distribution:
    email: true
    dashboard: true
    file_export: true

  # Recipients
  recipients:
    - "risk_manager"
    - "portfolio_manager"
    - "compliance"

# Risk Model Parameters
risk_model:
  # VaR calculation
  var_calculation:
    method: "monte_carlo"       # historical, parametric, monte_carlo
    confidence_level: 0.95
    holding_period: 1           # 1 day

    # Monte Carlo parameters
    monte_carlo:
      num_simulations: 10000
      random_seed: 42

    # Historical parameters
    historical:
      lookback_period: 252      # 1 year
      decay_factor: 0.94

  # Covariance matrix
  covariance_matrix:
    estimation_method: "ledoit_wolf"  # sample, ledoit_wolf, oas
    lookback_period: 252
    min_periods: 60

  # Expected returns
  expected_returns:
    method: "capm"              # historical, capm, black_litterman
    lookback_period: 252

  # Model validation
  validation:
    enabled: true
    backtesting_period: 252
    confidence_level: 0.95

# Compliance and Governance
compliance:
  enabled: true

  # Regulatory requirements
  regulatory:
    # SEC requirements
    sec_compliance: true

    # FINRA requirements
    finra_compliance: true

    # Internal policies
    internal_policies: true

  # Audit trail
  audit_trail:
    enabled: true
    retention_period: 2555      # 7 years

  # Risk committee
  risk_committee:
    meeting_frequency: "monthly"
    risk_review_required: true

  # Documentation
  documentation:
    policy_updates: true
    procedure_documentation: true
    training_records: true
