# Alerting Configuration
# Centralized configuration for all alert channels and settings

alerting:
  enabled_channels: ['log_only', 'slack']
  throttle_seconds: 300  # Prevent alert spam

  slack:
    webhook_url: ${SLACK_WEBHOOK_URL}
    channel: '#alerts'
    username: 'AI Trader Alert'
    icon_emoji: ':chart_with_upwards_trend:'

    # Alert level customization
    alert_colors:
      info: '#36a64f'
      warning: '#ff9900'
      error: '#ff0000'
      critical: '#8b0000'

    # Thread messages by category
    thread_by_category: true
    categories:
      - data_pipeline
      - trading
      - risk
      - system

  email:
    smtp_host: ${SMTP_HOST}
    smtp_port: 587
    from_address: ${ALERT_EMAIL_FROM}
    recipients: ${ALERT_EMAIL_RECIPIENTS}
    use_tls: true

    # Email templates
    templates:
      default: 'plain'
      critical: 'html'

    # Batch settings
    batch_alerts: true
    batch_interval_minutes: 60
    max_batch_size: 50

  pagerduty:
    api_key: ${PAGERDUTY_API_KEY}
    service_id: ${PAGERDUTY_SERVICE_ID}

    # Only for critical alerts
    severity_filter: ['critical']

    # Deduplication
    dedup_window_minutes: 30

  sms:
    provider: 'twilio'
    account_sid: ${TWILIO_ACCOUNT_SID}
    auth_token: ${TWILIO_AUTH_TOKEN}
    from_number: ${TWILIO_FROM_NUMBER}
    to_numbers: ${SMS_ALERT_NUMBERS}

    # SMS is expensive - strict filtering
    enabled: false
    severity_filter: ['critical']
    cost_limit_daily: 10.0

# Alert severity definitions
severity_definitions:
  info:
    notify_channels: ['log_only']
    throttle_minutes: 60

  warning:
    notify_channels: ['log_only', 'slack']
    throttle_minutes: 30

  error:
    notify_channels: ['log_only', 'slack', 'email']
    throttle_minutes: 15

  critical:
    notify_channels: ['log_only', 'slack', 'email', 'pagerduty']
    throttle_minutes: 5

# Alert rules
alert_rules:
  # Data pipeline alerts
  data_pipeline:
    backfill_failure:
      severity: error
      template: "Backfill failed for {symbol}: {error_message}"

    data_gap_detected:
      severity: warning
      template: "Data gap detected for {symbol}: {gap_hours} hours missing"

    api_rate_limit:
      severity: warning
      template: "API rate limit approaching for {source}: {current}/{limit}"

  # Trading alerts
  trading:
    position_limit_breach:
      severity: critical
      template: "Position limit breached: {symbol} position {current_size} exceeds {limit}"

    order_rejected:
      severity: error
      template: "Order rejected: {order_id} for {symbol} - {reason}"

  # System alerts
  system:
    high_memory_usage:
      severity: warning
      template: "High memory usage: {current_mb}MB / {limit_mb}MB ({percent}%)"

    database_connection_failure:
      severity: critical
      template: "Database connection failed: {error_message}"
