# Scanner Configuration
# Configuration for Layer 2-3 scanning system

scanners:
  # Global scanner settings
  global:
    cache_ttl_seconds: 60
    enable_caching: true
    batch_size: 100
    max_concurrent_scans: 5

  # Layer 2 Catalyst Orchestrator Configuration
  layer2:
    min_final_score: 3.0  # Minimum aggregate score to qualify
    max_scanners_concurrent: 10
    timeout_seconds: 30

  # Orchestrator settings
  orchestrator:
    catalyst_scoring:
      scaling:
        alert_score_multiplier: 5.0  # Convert 0-1 scores to 0-5 scale
        score_normalization_divisor: 10.0  # Normalize final scores back to 0-1
        emerging_score_base: 0.4
        emerging_score_divisor: 20.0
      weighting:
        layer2_confidence_weight: 0.7
        layer1_confidence_weight: 0.3
        high_signal_boost_factor: 1.2
        medium_signal_boost_factor: 1.1
      thresholds:
        strong_signal_threshold: 5.0
        emerging_catalyst_threshold: 1.5
        min_layer1_signals: 2
        signal_boost_threshold_high: 5
        signal_boost_threshold_medium: 3

  # Individual Scanner Configurations

  # News Scanner
  news:
    enabled: true
    priority: 9
    lookback_hours: 24
    min_sentiment_score: 0.7
    use_cache: true
    dedup_window_hours: 48
    impact_weights:
      upgrade: 0.9
      downgrade: 0.8
      earnings_beat: 0.85
      earnings_miss: 0.8
      acquisition: 0.9
      partnership: 0.7
      product_launch: 0.6
      regulatory: 0.8
      general: 0.5
    classification_keywords:
      upgrade: ['upgrade', 'raised', 'buy rating', 'outperform']
      downgrade: ['downgrade', 'lowered', 'sell rating', 'underperform']
      earnings: ['earnings', 'revenue', 'eps', 'beat', 'miss', 'guidance']
      acquisition: ['acquisition', 'merger', 'buyout', 'acquired']
      partnership: ['partnership', 'collaboration', 'agreement', 'deal']
      product: ['launch', 'release', 'announce', 'introduce', 'unveil']
      regulatory: ['fda', 'sec', 'regulatory', 'approval', 'investigation']

  # Technical Scanner
  technical:
    enabled: true
    priority: 8
    breakout_pct: 2.0
    gap_pct: 2.0
    lookback_days: 30
    volume_confirmation: true
    min_price: 5.0
    use_cache: true
    indicators:
      - sma_20
      - sma_50
      - rsi
      - bollinger_bands

  # Volume Scanner
  volume:
    enabled: true
    priority: 8
    lookback_days: 20
    min_relative_volume: 2.0  # 2x average volume
    min_absolute_volume: 1000000
    use_cache: true
    volume_surge_threshold: 3.0  # 3x for surge alert

  # Earnings Scanner
  earnings:
    enabled: true
    priority: 9
    days_before_earnings: 5
    days_after_earnings: 2
    min_surprise_pct: 5.0
    use_cache: true

  # Insider Scanner
  insider:
    enabled: true
    priority: 9
    lookback_days: 30
    min_transaction_value: 100000
    cluster_window_days: 7
    min_cluster_size: 3
    use_cache: true

  # Options Scanner
  options:
    enabled: true
    priority: 8
    lookback_hours: 8
    min_unusual_ratio: 2.0
    min_oi_change: 1000
    min_premium: 50000
    use_cache: true

  # Social Scanner
  social:
    enabled: true
    priority: 7
    lookback_hours: 24
    min_mentions: 100
    surge_multiplier: 3.0
    sentiment_threshold: 0.7
    platforms:
      - reddit
      - twitter
      - stocktwits
    use_cache: true

  # Sector Scanner
  sector:
    enabled: true
    priority: 7
    lookback_days: 5
    min_sector_move_pct: 2.0
    correlation_threshold: 0.7
    use_cache: true

  # Intermarket Scanner
  intermarket:
    enabled: true
    priority: 6
    lookback_days: 20
    correlation_window: 60
    divergence_threshold: 2.0
    markets_to_track:
      - SPY
      - DXY
      - GLD
      - TLT
      - VIX
    use_cache: true

  # Market Validation Scanner
  market_validation:
    enabled: true
    priority: 6
    confirmation_threshold: 0.7
    divergence_penalty: 0.3
    use_cache: true

  # Coordinated Activity Scanner
  coordinated_activity:
    enabled: true
    priority: 8
    correlation_threshold: 0.8
    time_window_minutes: 30
    min_symbols: 3
    use_cache: true

  # Advanced Sentiment Scanner
  advanced_sentiment:
    enabled: true
    priority: 7
    sentiment_sources:
      - news
      - social
      - analyst
    aggregation_method: weighted_average
    min_composite_score: 0.7
    use_cache: true

# Data source configurations for scanners
data_sources:
  market_data:
    hot_storage_days: 30  # Recent data in PostgreSQL
    cold_storage_enabled: true  # Historical data in data lake

  news:
    sources:
      - polygon
    hot_storage_days: 7

  social:
    hot_storage_days: 3

  alternative:
    hot_storage_days: 30
