# Development Environment Configuration
# Overrides for local development

system:
  environment: paper
  debug:
    log_level: DEBUG
    polygon_trace: true

broker:
  paper_trading: true

database:
  host: localhost
  port: 5432
  name: ai_trader_dev

# Enable all debugging and development features
features:
  enable_ml_models: true
  enable_backtesting: true
  enable_advanced_analytics: true
  enable_experimental_features: true

# More aggressive data collection for development
data:
  backfill:
    max_parallel: 10
  streaming:
    enabled: true

# Development-friendly risk settings
risk:
  position_sizing:
    max_position_size: 1000.0  # Lower for development
  circuit_breaker:
    daily_loss_limit: 1.0  # 1% limit for development

# Enhanced monitoring for debugging
monitoring:
  metrics_enabled: true
  performance_tracking: true
  trace_sampling_rate: 1.0  # 100% sampling in dev