# Paper Trading Environment Configuration
# Production-like settings but with paper trading

system:
  environment: paper
  debug:
    log_level: INFO
    polygon_trace: false

broker:
  paper_trading: true

database:
  host: ${oc.env:DB_HOST}
  port: ${oc.env:DB_PORT}
  name: ${oc.env:DB_NAME}

# Production feature settings
features:
  enable_ml_models: true
  enable_backtesting: true
  enable_advanced_analytics: true
  enable_experimental_features: false  # Disable experimental in paper

# Balanced data collection
data:
  backfill:
    max_parallel: 20
  streaming:
    enabled: true

# Production-like risk settings
risk:
  position_sizing:
    max_position_size: 5000.0
  circuit_breaker:
    daily_loss_limit: 3.0  # 3% limit for paper trading

# Standard monitoring
monitoring:
  metrics_enabled: true
  performance_tracking: true
  trace_sampling_rate: 0.1  # 10% sampling