# Production Environment Configuration
# Live trading settings - USE WITH EXTREME CAUTION

system:
  environment: live
  debug:
    log_level: WARNING
    polygon_trace: false

broker:
  paper_trading: false  # LIVE TRADING ENABLED

database:
  host: ${oc.env:PROD_DB_HOST}
  port: ${oc.env:PROD_DB_PORT}
  name: ${oc.env:PROD_DB_NAME}

# Conservative feature settings for production
features:
  enable_ml_models: true
  enable_backtesting: false  # Disable in production
  enable_advanced_analytics: true
  enable_experimental_features: false  # Never in production

# Conservative data collection
data:
  backfill:
    max_parallel: 15  # Lower to avoid rate limits
  streaming:
    enabled: true

# Strict risk settings for live trading
risk:
  position_sizing:
    max_position_size: 2000.0  # Conservative position sizes
  limits:
    max_daily_trades: 20  # Limit daily activity
    max_positions: 10
  circuit_breaker:
    enabled: true
    daily_loss_limit: 2.0  # 2% max daily loss
  stop_loss:
    enabled: true
    default_percentage: 1.5  # Tight stop losses

# Production monitoring
monitoring:
  metrics_enabled: true
  performance_tracking: true
  trace_sampling_rate: 0.01  # 1% sampling for performance

# Production alerting (stricter thresholds)
alerting:
  error_threshold: 0.5  # Alert on any errors
  performance_threshold: 1000  # ms
  position_size_alert: 1500.0  # Alert on large positions