# AI Trader - Pre-commit hooks configuration
# Ensures code quality and consistency before commits

repos:
  # Pre-commit hooks for general file hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]  # Allow custom YAML tags used by Hydra
      - id: check-toml
      - id: check-json
      - id: check-xml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-added-large-files
        args: [--maxkb=1024]  # Prevent large files (1MB limit)
      - id: forbid-new-submodules
      - id: no-commit-to-branch
        args: [--branch, main, --branch, master, --branch, production]

  # Python code formatting with Black
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88]

  # Import sorting with isort
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile, black, --line-length, '88']

  # Python linting with flake8
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=88, --extend-ignore=E203,W503]
        additional_dependencies:
          - flake8-bugbear>=23.7.10
          - flake8-comprehensions>=3.14.0
          - flake8-simplify>=0.20.0
          - flake8-bandit>=4.1.1

  # Security vulnerability scanning
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [-r, src/ai_trader]
        exclude: ^tests/

  # Type checking with mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.0
    hooks:
      - id: mypy
        args: [--config-file=pyproject.toml]
        additional_dependencies:
          - types-requests>=2.31.0
          - types-python-dateutil>=2.8.0
          - types-pytz>=2023.3.0
          - types-redis>=4.6.0
        files: ^src/main/

  # Upgrade Python syntax for newer versions
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

  # Remove unused imports
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.0
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variables
          - --remove-duplicate-keys
          - --ignore-init-module-imports

  # Docstring formatting
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        args:
          - --in-place
          - --wrap-summaries=88
          - --wrap-descriptions=88
          - --pre-summary-newline
          - --make-summary-multi-line

  # Spell checking for documentation
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        args:
          - --skip=*.css,*.js,*.html,*.svg,data_lake,models,logs,venv
          - --ignore-words-list=te,fo,fpr,ot,nd,nam

  # YAML formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.1
    hooks:
      - id: prettier
        types: [yaml]
        exclude: ^(data_lake|models|logs)/

  # Shell script linting
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.5
    hooks:
      - id: shellcheck
        files: \.(sh|bash)$

  # Requirements.txt formatting and validation
  - repo: https://github.com/pre-commit/mirrors-pip-compile
    rev: v7.1.0
    hooks:
      - id: pip-compile
        files: ^requirements\.in$
        args: [--generate-hashes, --allow-unsafe]

  # Jupyter notebook cleaning (if any notebooks are added later)
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout

# Global settings
default_stages: [commit]
default_language_version:
  python: python3

# Files and directories to exclude from all hooks
exclude: |
  (?x)^(
      data_lake/.*|
      models/.*|
      logs/.*|
      venv/.*|
      env/.*|
      \.venv/.*|
      build/.*|
      dist/.*|
      \.eggs/.*|
      \.git/.*|
      \.mypy_cache/.*|
      \.pytest_cache/.*|
      \.tox/.*|
      __pycache__/.*|
      .*\.egg-info/.*
  )$

# Minimum pre-commit version
minimum_pre_commit_version: 3.3.0

# Configure specific tools
ci:
  # Pre-commit.ci configuration
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false