# Prometheus Alert Rules for AI Trader
groups:
  - name: ai_trader_alerts
    rules:
      # System Health Alerts
      - alert: AITraderDown
        expr: up{job="ai-trader"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "AI Trader system is down"
          description: "AI Trader has been down for more than 30 seconds"

      - alert: DataPipelineUnhealthy
        expr: ai_trader_data_pipeline_healthy == 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Data pipeline is unhealthy"
          description: "Data pipeline has been unhealthy for more than 2 minutes"

      # Trading Performance Alerts
      - alert: HighDailyLoss
        expr: ai_trader_daily_pnl < -2000
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High daily loss detected"
          description: "Daily loss is {{ $value }} USD, exceeding threshold"

      - alert: CircuitBreakerTriggered
        expr: ai_trader_circuit_breaker_triggered == 1
        for: 0s
        labels:
          severity: critical
        annotations:
          summary: "Trading circuit breaker triggered"
          description: "Circuit breaker has been triggered, trading halted"

      - alert: TooManyActivePositions
        expr: ai_trader_active_positions > 20
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Too many active positions"
          description: "{{ $value }} active positions, exceeding recommended limit"

      # Technical Alerts
      - alert: HighErrorRate
        expr: rate(ai_trader_errors_total[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }} errors/sec over the last 5 minutes"

      - alert: SlowAPIResponse
        expr: avg(ai_trader_api_response_time_seconds) > 5
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "Slow API response times"
          description: "Average API response time is {{ $value }}s"

      - alert: DatabaseConnectionIssue
        expr: ai_trader_database_connections_active / ai_trader_database_connections_max > 0.8
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Database connection pool nearly exhausted"
          description: "Using {{ $value }}% of available database connections"

      # Live Trading Specific Alerts (only for production)
      - alert: LiveTradingPositionSizeAlert
        expr: ai_trader_position_size > 5000 and on() ai_trader_environment == "live"
        for: 0s
        labels:
          severity: critical
        annotations:
          summary: "Large position size in live trading"
          description: "Position size of {{ $value }} USD in live trading mode"

      - alert: UnexpectedLiveTrading
        expr: ai_trader_paper_trading == 0 and on() ai_trader_environment != "live"
        for: 0s
        labels:
          severity: critical
        annotations:
          summary: "Live trading enabled outside production"
          description: "Live trading is enabled in {{ $labels.environment }} environment"

  - name: ai_trader_data_quality
    rules:
      # Data Quality Alerts
      - alert: StaleMarketData
        expr: time() - ai_trader_last_market_data_update > 300
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Stale market data"
          description: "Market data has not been updated for {{ $value }} seconds"

      - alert: MissingSymbolData
        expr: ai_trader_symbols_with_data / ai_trader_symbols_total < 0.95
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Missing data for symbols"
          description: "Only {{ $value }}% of symbols have current data"

      - alert: DataIngestionBacklog
        expr: ai_trader_data_ingestion_queue_size > 1000
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Data ingestion backlog"
          description: "{{ $value }} items in data ingestion queue"