# File: config/universe_definitions.yaml
# This file contains static lists and definitions related to symbol universes.
# Separated from main config to avoid "god config" anti-pattern

universe_data:
  # Popular stocks for quick testing and validation
  popular_stocks:
    - AAPL   # Apple Inc.
    - MSFT   # Microsoft Corporation
    - GOOGL  # Alphabet Inc.
    - AMZN   # Amazon.com Inc.
    - NVDA   # NVIDIA Corporation
    - META   # Meta Platforms Inc.
    - TSLA   # Tesla Inc.
    - BRK.B  # Berkshire Hathaway
    - JPM    # JPMorgan Chase
    - JNJ    # Johnson & Johnson
    - V      # Visa Inc.
    - WMT    # Walmart Inc.
    - PG     # Procter & Gamble
    - MA     # Mastercard Inc.
    - HD     # Home Depot
    - UNH    # UnitedHealth Group
    - DIS    # Walt Disney Company
    - BAC    # Bank of America
    - NFLX   # Netflix Inc.
    - ADBE   # Adobe Inc.

  # Sector mappings for diversification and analysis
  sector_mappings:
    Technology:
      - AAPL
      - MSFT
      - GOOGL
      - NVDA
      - META
      - AVGO
      - ORCL
      - ADBE
      - CRM
      - INTC
      - AMD
      - QCOM
      - IBM
      - NOW
      - CSCO
      
    Healthcare:
      - UNH
      - JNJ
      - LLY
      - PFE
      - ABBV
      - TMO
      - MRK
      - ABT
      - CVS
      - MDT
      - DHR
      - AMGN
      - BMY
      - GILD
      - ISRG
      
    Financials:
      - BRK.B
      - JPM
      - BAC
      - WFC
      - GS
      - MS
      - SCHW
      - AXP
      - C
      - BLK
      - CB
      - PGR
      - MMC
      - MET
      - USB
      
    Consumer_Discretionary:
      - AMZN
      - TSLA
      - HD
      - MCD
      - NKE
      - SBUX
      - LOW
      - TJX
      - BKNG
      - GM
      - F
      - MAR
      - CMG
      - YUM
      - ORLY
      
    Consumer_Staples:
      - WMT
      - PG
      - KO
      - PEP
      - COST
      - PM
      - MO
      - MDLZ
      - CL
      - GIS
      - KMB
      - STZ
      - KDP
      - SYY
      - ADM
      
    Energy:
      - XOM
      - CVX
      - COP
      - SLB
      - EOG
      - MPC
      - PSX
      - VLO
      - OXY
      - KMI
      - WMB
      - HAL
      - DVN
      - HES
      - BKR
      
    Industrials:
      - BA
      - RTX
      - HON
      - UPS
      - CAT
      - LMT
      - GE
      - MMM
      - DE
      - FDX
      - EMR
      - ITW
      - NSC
      - GD
      - PH
      
    Communication_Services:
      - DIS
      - CMCSA
      - NFLX
      - VZ
      - T
      - TMUS
      - CHTR
      - EA
      - TTWO
      - ATVI
      - WBD
      - PARA
      - FOX
      - FOXA
      - OMC
      
    Utilities:
      - NEE
      - DUK
      - SO
      - D
      - AEP
      - EXC
      - SRE
      - XEL
      - ED
      - WEC
      - ES
      - AWK
      - DTE
      - PPL
      - AEE
      
    Real_Estate:
      - AMT
      - PLD
      - CCI
      - EQIX
      - PSA
      - O
      - SBAC
      - WELL
      - DLR
      - AVB
      - EQR
      - VTR
      - INVH
      - ARE
      - MAA
      
    Materials:
      - LIN
      - APD
      - SHW
      - FCX
      - ECL
      - NEM
      - DOW
      - PPG
      - DD
      - NUE
      - CTVA
      - VMC
      - MLM
      - BALL
      - ALB


  # Universe filters for dynamic selection
  universe_filters:
    # Quality filters
    quality:
      min_market_cap: 1000000000     # $1B minimum
      min_avg_volume: 1000000         # 1M shares daily (from symbol_selection_config)
      min_price: 5.0                  # $5 minimum
      max_price: 1000.0               # $1K maximum (from symbol_selection_config)
      
    # Liquidity filters  
    liquidity:
      min_dollar_volume: 5000000      # $5M daily dollar volume
      min_trades_per_day: 1000        # 1K trades minimum
      max_spread_percent: 0.5         # 0.5% max bid-ask spread
      
    # Risk filters
    risk:
      exclude_penny_stocks: true      # Exclude < $5
      exclude_otc: true               # Exclude OTC stocks
      exclude_etfs: false             # Include ETFs
      exclude_foreign_adrs: false     # Include ADRs
      
  # Special universes for different strategies
  special_universes:
    # High volume day trading universe
    day_trading:
      min_avg_volume: 10000000        # 10M shares
      min_dollar_volume: 100000000    # $100M daily
      max_spread_percent: 0.1         # 0.1% tight spreads
      
    # Swing trading universe  
    swing_trading:
      min_market_cap: 10000000000     # $10B+ for stability
      min_avg_volume: 2000000         # 2M shares
      volatility_range: [0.02, 0.05]  # 2-5% daily volatility
      
    # Value investing universe
    value_investing:
      min_market_cap: 5000000000      # $5B+ established companies
      min_years_public: 5             # 5+ years of history
      profitability_required: true    # Must be profitable
      
    # Growth universe
    growth_investing:
      min_revenue_growth: 0.15        # 15%+ revenue growth
      min_market_cap: 1000000000      # $1B+ market cap
      max_pe_ratio: 50                # Reasonable valuation

  # ETF universes for sector/factor exposure
  etf_universes:
    sector_etfs:
      - XLK   # Technology Select Sector SPDR
      - XLV   # Health Care Select Sector SPDR
      - XLF   # Financial Select Sector SPDR
      - XLY   # Consumer Discretionary Select SPDR
      - XLP   # Consumer Staples Select Sector SPDR
      - XLE   # Energy Select Sector SPDR
      - XLI   # Industrial Select Sector SPDR
      - XLC   # Communication Services Select Sector SPDR
      - XLU   # Utilities Select Sector SPDR
      - XLRE  # Real Estate Select Sector SPDR
      - XLB   # Materials Select Sector SPDR
      
    factor_etfs:
      - MTUM  # Momentum Factor ETF
      - QUAL  # Quality Factor ETF
      - VLUE  # Value Factor ETF
      - SIZE  # Size Factor ETF
      - USMV  # Minimum Volatility ETF
      
    index_etfs:
      - SPY   # S&P 500 ETF
      - QQQ   # Nasdaq 100 ETF
      - IWM   # Russell 2000 ETF
      - DIA   # Dow Jones ETF
      - VTI   # Total Market ETF
      
  # Symbol selection scoring (from symbol_selection_config.yaml)
  symbol_selection:
    # Minimum requirements
    min_data_completeness: 0.95  # 95% of expected data points
    lookback_days: 252           # 1 year of history
    min_score: 60.0              # Minimum score to be selected
    
    # Scoring weights (must sum to 1.0)
    scoring_weights:
      data_quality: 0.2    # Weight for data completeness/quality
      liquidity: 0.3       # Weight for volume/tradability
      volatility: 0.1      # Weight for volatility (moderate is best)
      strategy_fit: 0.4    # Weight for strategy performance
      
    # Diversification settings
    diversification:
      enabled: true
      max_per_sector:
        Technology: 50
        Healthcare: 40
        Financials: 40
        Consumer_Discretionary: 30
        Consumer_Staples: 30
        Industrials: 30
        Energy: 20
        Communication_Services: 20
        Utilities: 20
        Materials: 20
        Real_Estate: 20

# Universe Configuration (merged from universe.yaml)
# Defines the investment universe and filtering criteria
universe:
  # Default universe definition
  default:
    name: "US_EQUITIES_LARGE_CAP"
    description: "Large cap US equities with high liquidity"
    
  # Universe filters
  filters:
    market_cap:
      min: 1000000000  # $1B minimum market cap
      max: null        # No maximum
    
    price:
      min: 5.0         # $5 minimum price
      max: null        # No maximum
    
    volume:
      min_avg_volume: 1000000  # 1M average daily volume
      lookback_days: 30
    
    exchange:
      allowed:
        - "NASDAQ"
        - "NYSE"
        - "AMEX"
      blocked: []
    
    sector:
      allowed: []      # Empty means all sectors allowed
      blocked:
        - "UTILITIES"  # Generally low volatility
    
    fundamental:
      min_revenue: 100000000    # $100M minimum revenue
      exclude_penny_stocks: true
      exclude_otc: true
      exclude_pink_sheets: true
  
  # Predefined universe sets
  universes:
    large_cap:
      name: "Large Cap"
      market_cap:
        min: 10000000000  # $10B
      price:
        min: 20.0
      volume:
        min_avg_volume: 2000000
    
    mid_cap:
      name: "Mid Cap"
      market_cap:
        min: 2000000000   # $2B
        max: 10000000000  # $10B
      price:
        min: 10.0
      volume:
        min_avg_volume: 500000
    
    small_cap:
      name: "Small Cap"
      market_cap:
        min: 300000000    # $300M
        max: 2000000000   # $2B
      price:
        min: 5.0
      volume:
        min_avg_volume: 100000
    
    growth_stocks:
      name: "Growth Stocks"
      market_cap:
        min: 1000000000
      fundamental:
        min_revenue_growth: 0.15  # 15% revenue growth
        max_pe_ratio: 50
      
    value_stocks:
      name: "Value Stocks"
      market_cap:
        min: 1000000000
      fundamental:
        max_pe_ratio: 20
        min_dividend_yield: 0.02  # 2% dividend yield
    
    momentum_stocks:
      name: "Momentum Stocks"
      market_cap:
        min: 1000000000
      technical:
        min_price_momentum_3m: 0.10  # 10% price momentum over 3 months
        min_volume_momentum: 1.5     # 1.5x average volume
    
    high_volume:
      name: "High Volume Stocks"
      volume:
        min_avg_volume: 5000000  # 5M average daily volume
      price:
        min: 10.0
    
    sp500:
      name: "S&P 500"
      source: "sp500_constituents"
      # Will be populated from external source
    
    nasdaq100:
      name: "NASDAQ 100"
      source: "nasdaq100_constituents"
      # Will be populated from external source

# Dynamic universe management
dynamic_filtering:
  enabled: true
  
  # Rebalancing schedule
  rebalance:
    frequency: "weekly"  # daily, weekly, monthly
    day: "monday"        # For weekly rebalancing
    
  # Automatic exclusions
  auto_exclude:
    # Exclude stocks with recent earnings
    earnings_buffer_days: 2
    
    # Exclude stocks with recent splits/dividends
    corporate_action_buffer_days: 5
    
    # Exclude stocks with low relative volume
    min_relative_volume: 0.5
    
    # Exclude stocks with wide spreads
    max_bid_ask_spread_pct: 0.02  # 2%
    
    # Exclude stocks with recent IPOs
    min_trading_days: 60
  
  # Quality checks
  quality_filters:
    # Data quality requirements
    min_data_completeness: 0.95  # 95% data completeness
    max_price_gaps: 0.05         # 5% max price gaps
    
    # Trading activity requirements
    min_trading_days_per_month: 20
    max_halt_days_per_month: 2

# Watchlists (from universe.yaml)
watchlists:
  favorites:
    name: "Favorite Stocks"
    symbols:
      - "AAPL"
      - "MSFT"
      - "GOOGL"
      - "AMZN"
      - "TSLA"
      - "META"
      - "NVDA"
  
  meme_stocks:
    name: "Meme Stocks"
    symbols:
      - "GME"
      - "AMC"
      - "BB"
      - "PLTR"
      - "WISH"
  
  etfs:
    name: "ETFs"
    symbols:
      - "SPY"
      - "QQQ"
      - "IWM"
      - "VTI"
      - "VOO"

# Performance monitoring (from universe.yaml)
monitoring:
  universe_health:
    check_frequency: "daily"
    alert_thresholds:
      min_universe_size: 100
      max_universe_size: 2000
      min_avg_volume: 500000
      max_concentration_pct: 0.10  # No single stock > 10%
  
  data_quality:
    check_frequency: "hourly"
    alert_thresholds:
      min_data_completeness: 0.90
      max_stale_data_hours: 6